name: Merge Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types:
      - ready_for_review
      - assigned

jobs:
  oss-maven-workflow:
    uses: LimeMojito/oss-maven-standards/.github/workflows/oss-java-build.yml@master
    secrets: inherit
